import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,
  machines: defineTable({
    capabilityCeiling: v.optional(v.array(v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task")))),
    deviceToken: v.optional(v.string()),
    deviceTokenHash: v.optional(v.string()),
    name: v.string(),
    ownerId: v.optional(v.id("users")),
    platform: v.union(v.literal("darwin"), v.literal("linux"), v.literal("win32")),
    daemonVersion: v.string(),
    lastHeartbeatAt: v.number(),
    revokedAt: v.optional(v.number()),
  }).index("by_device_token", ["deviceToken"]).index("by_device_token_hash", ["deviceTokenHash"]).index("by_owner", ["ownerId"]),
  machineTelemetry: defineTable({
    activeLeases: v.number(),
    authFailures: v.number(),
    crossOwnerResults: v.number(),
    duplicateCommands: v.number(),
    fallbackActivations: v.number(),
    mode: v.union(v.literal("legacy"), v.literal("shadow"), v.literal("kernel")),
    pendingEffects: v.number(),
    projectionBacklog: v.number(),
    projectionDivergences: v.number(),
    projectionGaps: v.number(),
    recoverableFailures: v.number(),
    reportedAt: v.number(),
    sandboxViolations: v.number(),
    unrecoverableFailures: v.number(),
    machineId: v.id("machines"),
  }).index("by_machine", ["machineId"]),
  pairings: defineTable({
    codeHash: v.string(),
    deviceTokenHash: v.string(),
    // Optional only for deploy compatibility with pre-deviceNonce records.
    // New pairing writes and machine registration still require a match.
    deviceNonce: v.optional(v.string()),
    expiresAt: v.number(),
    ownerId: v.optional(v.id("users")),
    status: v.union(v.literal("waiting"), v.literal("claimed")),
  }).index("by_code_hash", ["codeHash"]).index("by_device_token_hash", ["deviceTokenHash"]).index("by_nonce", ["deviceNonce"]).index("by_expires_at", ["expiresAt"]).index("by_status", ["status"]),
  projects: defineTable({
    archivedAt: v.optional(v.number()),
    error: v.optional(v.string()),
    machineId: v.id("machines"),
    name: v.string(),
    path: v.string(),
    status: v.optional(v.union(v.literal("pending"), v.literal("active"), v.literal("error"))),
    trustRequestedAt: v.optional(v.number()),
    trustState: v.optional(v.union(v.literal("requested"), v.literal("trusted"), v.literal("untrusted"))),
  }).index("by_machine", ["machineId"]).index("by_machine_path", ["machineId", "path"]),
  mcpServers: defineTable({
    approvalThreadId: v.id("threads"),
    enabled: v.boolean(),
    authorizationUrl: v.optional(v.string()),
    error: v.optional(v.string()),
    name: v.string(),
    projectId: v.id("projects"),
    status: v.union(v.literal("disconnected"), v.literal("connecting"), v.literal("authorizing"), v.literal("connected"), v.literal("error")),
    toolCount: v.optional(v.number()),
    transport: v.union(
      v.object({ authEnvVar: v.optional(v.string()), kind: v.literal("http"), oauthIssuer: v.optional(v.string()), url: v.string() }),
      v.object({ args: v.array(v.string()), command: v.string(), cwd: v.optional(v.string()), envVarNames: v.optional(v.array(v.string())), kind: v.literal("stdio") }),
    ),
  }).index("by_project", ["projectId"]).index("by_approval_thread_id", ["approvalThreadId"]),
  mcpElicitations: defineTable({
    promptsJson: v.string(),
    responseJson: v.optional(v.string()),
    resumeStatus: v.union(v.literal("idle"), v.literal("queued"), v.literal("running"), v.literal("stopped"), v.literal("done"), v.literal("failed")),
    serverId: v.string(),
    status: v.union(v.literal("pending"), v.literal("submitted"), v.literal("cancelled")),
    threadId: v.id("threads"),
    toolName: v.string(),
  }).index("by_thread", ["threadId"]),
  threads: defineTable({
    activeAssistantMessageId: v.optional(v.id("messages")),
    budgetUsd: v.optional(v.number()),
    modelId: v.optional(v.string()),
    mode: v.optional(v.union(v.literal("chat"), v.literal("plan"))),
    permissionProfile: v.optional(v.union(v.literal("read-only"), v.literal("workspace-write"), v.literal("full-access"))),
    planModelId: v.optional(v.string()),
    buildModelId: v.optional(v.string()),
    planPhase: v.optional(v.union(v.literal("planning"), v.literal("review"), v.literal("building"), v.literal("complete"))),
    projectId: v.id("projects"),
    status: v.union(v.literal("idle"), v.literal("queued"), v.literal("running"), v.literal("awaiting-approval"), v.literal("restoring"), v.literal("stopped"), v.literal("done"), v.literal("failed")),
    stopRequested: v.optional(v.boolean()),
    title: v.string(),
    thinkingLevel: v.optional(v.union(v.literal("none"), v.literal("low"), v.literal("medium"), v.literal("high"))),
    usageTotals: v.optional(v.object({
      cacheReadTokens: v.number(),
      cacheWriteTokens: v.number(),
      costUsd: v.number(),
      inputTokens: v.number(),
      outputTokens: v.number(),
      thinkingTokens: v.number(),
      thinkingTokensUnavailableCalls: v.number(),
    })),
  }).index("by_project", ["projectId"]),
  plans: defineTable({
    content: v.string(),
    revision: v.number(),
    status: v.union(v.literal("draft"), v.literal("approved")),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]),
  messages: defineTable({
    content: v.string(),
    queuedThreadId: v.optional(v.id("threads")),
    role: v.union(v.literal("assistant"), v.literal("user")),
    status: v.union(v.literal("complete"), v.literal("queued"), v.literal("streaming")),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]).index("by_status", ["status"]).index("by_queued_thread", ["queuedThreadId"]),
  events: defineTable({
    checkpointId: v.optional(v.id("checkpoints")),
    kind: v.union(v.literal("checkpoint.reverted"), v.literal("command.output"), v.literal("mcp.task"), v.literal("tool.completed")),
    output: v.optional(v.string()),
    summary: v.optional(v.string()),
    serverId: v.optional(v.string()),
    status: v.optional(v.string()),
    taskId: v.optional(v.string()),
    threadId: v.id("threads"),
    tool: v.optional(v.union(v.literal("bash"), v.literal("edit"), v.literal("glob"), v.literal("grep"), v.literal("mcp"), v.literal("read"), v.literal("skill"), v.literal("str_replace"), v.literal("task"), v.literal("todo"), v.literal("web_fetch"), v.literal("web_search"))),
  }).index("by_thread", ["threadId"]),
  commands: defineTable({
    command: v.string(),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    threadId: v.id("threads"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]),
  diffs: defineTable({
    content: v.string(),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]),
  diffComments: defineTable({
    content: v.string(),
    endLine: v.number(),
    filePath: v.string(),
    resolved: v.boolean(),
    startLine: v.number(),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]),
  approvals: defineTable({
    capability: v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task"), v.literal("search")),
    decision: v.union(v.literal("pending"), v.literal("allow"), v.literal("deny")),
    risk: v.union(v.literal("low"), v.literal("high"), v.literal("critical")),
    continuationJson: v.optional(v.string()),
    resumeStatus: v.optional(v.union(v.literal("idle"), v.literal("queued"), v.literal("running"), v.literal("stopped"), v.literal("done"), v.literal("failed"))),
    summary: v.string(),
    threadId: v.id("threads"),
    turnId: v.optional(v.string()),
  }).index("by_thread", ["threadId"]),
  auditLog: defineTable({
    action: v.optional(v.string()),
    actorId: v.optional(v.string()),
    actorKind: v.optional(v.union(v.literal("user"), v.literal("device"), v.literal("provider"), v.literal("system"))),
    capability: v.optional(v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task"), v.literal("search"))),
    causationId: v.optional(v.string()),
    category: v.optional(v.string()),
    correlationId: v.optional(v.string()),
    decision: v.optional(v.union(v.literal("allow"), v.literal("deny"), v.literal("ask"))),
    machineId: v.optional(v.id("machines")),
    policyVersion: v.optional(v.string()),
    projectId: v.optional(v.id("projects")),
    requestedScope: v.optional(v.string()),
    risk: v.optional(v.union(v.literal("low"), v.literal("high"), v.literal("critical"))),
    summary: v.optional(v.string()),
    threadId: v.optional(v.id("threads")),
    effectiveScope: v.optional(v.string()),
  }).index("by_thread", ["threadId"]).index("by_correlation", ["correlationId"]),
  gitActions: defineTable({
    action: v.union(v.literal("stage"), v.literal("commit"), v.literal("push")),
    message: v.optional(v.string()),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    threadId: v.id("threads"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]),
  checkpoints: defineTable({
    commit: v.string(),
    messageId: v.id("messages"),
    ref: v.string(),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]).index("by_message_id", ["messageId"]),
  checkpointActions: defineTable({
    checkpointId: v.id("checkpoints"),
    claimToken: v.optional(v.string()),
    leaseExpiresAt: v.optional(v.number()),
    resumeStatus: v.union(v.literal("idle"), v.literal("queued"), v.literal("stopped"), v.literal("done"), v.literal("failed")),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    threadId: v.id("threads"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]),
  checkpointComparisons: defineTable({
    claimToken: v.optional(v.string()),
    content: v.optional(v.string()),
    fromCheckpointId: v.id("checkpoints"),
    leaseExpiresAt: v.optional(v.number()),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    threadId: v.id("threads"),
    toCheckpointId: v.id("checkpoints"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]),
  usage: defineTable({
    cacheReadTokens: v.number(),
    cacheWriteTokens: v.number(),
    callId: v.string(),
    costUsd: v.number(),
    inputTokens: v.number(),
    messageId: v.id("messages"),
    modelId: v.string(),
    outputTokens: v.number(),
    role: v.string(),
    thinkingTokens: v.union(v.number(), v.null()),
    threadId: v.id("threads"),
  }).index("by_call_id", ["callId"]).index("by_thread", ["threadId"]),
  roles: defineTable({
    capabilities: v.array(v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task"))),
    contextMode: v.union(v.literal("fresh"), v.literal("forked")),
    description: v.string(),
    maxTurns: v.number(),
    modelId: v.string(),
    name: v.string(),
    prompt: v.string(),
    thinkingLevel: v.union(v.literal("none"), v.literal("low"), v.literal("medium"), v.literal("high")),
    writer: v.boolean(),
  }).index("by_name", ["name"]),
  subagentRuns: defineTable({
    capabilities: v.array(v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task"))),
    claimToken: v.optional(v.string()),
    depth: v.number(),
    leaseExpiresAt: v.optional(v.number()),
    machineId: v.optional(v.id("machines")),
    parentRunId: v.optional(v.id("subagentRuns")),
    result: v.optional(v.object({
      artifacts: v.array(v.string()),
      findings: v.array(v.string()),
      status: v.union(v.literal("success"), v.literal("failed")),
      summary: v.string(),
    })),
    roleId: v.id("roles"),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    task: v.string(),
    threadId: v.id("threads"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]).index("by_parent_run_id", ["parentRunId"]).index("by_machine", ["machineId", "status"]),

  // --- Kernel projection tables (widen-only — additive, no legacy changes) ---

  commandInbox: defineTable({
    commandId: v.optional(v.string()),
    completedAt: v.optional(v.number()),
    correlationId: v.string(),
    createdAt: v.number(),
    kind: v.string(),
    leaseExpiresAt: v.optional(v.number()),
    leaseOwner: v.optional(v.string()),
    leaseGeneration: v.optional(v.number()),
    machineId: v.optional(v.id("machines")),
    ownerId: v.optional(v.id("users")),
    payloadJson: v.string(),
    /** Authorized local workspace path copied from the thread's project at ingress. */
    projectPath: v.optional(v.string()),
    runId: v.optional(v.string()),
    status: v.union(v.literal("pending"), v.literal("claimed"), v.literal("completed"), v.literal("rejected")),
    threadId: v.optional(v.id("threads")),
  }).index("by_status_lease", ["status", "leaseExpiresAt"]).index("by_machine", ["machineId", "status"]).index("by_owner", ["ownerId"]).index("by_command_id", ["commandId"]),

  projectionEvents: defineTable({
    eventId: v.string(),
    machineId: v.optional(v.id("machines")),
    occurredAt: v.number(),
    ownerId: v.optional(v.id("users")),
    payloadJson: v.string(),
    publishedAt: v.number(),
    runId: v.string(),
    sequence: v.number(),
    type: v.string(),
    projectId: v.optional(v.id("projects")),
  }).index("by_run_sequence", ["runId", "sequence"]).index("by_project_run", ["projectId", "runId", "sequence"]).index("by_event_id", ["eventId"]).index("by_owner", ["ownerId"]).index("by_machine_run", ["machineId", "runId"]),

  projectionSnapshots: defineTable({
    machineId: v.optional(v.id("machines")),
    ownerId: v.optional(v.id("users")),
    runId: v.string(),
    sequence: v.number(),
    snapshotJson: v.string(),
    updatedAt: v.number(),
    projectId: v.optional(v.id("projects")),
  }).index("by_run", ["runId"]).index("by_project", ["projectId", "updatedAt"]).index("by_owner", ["ownerId"]).index("by_machine_run", ["machineId", "runId"]),

  projectionCursors: defineTable({
    direction: v.union(v.literal("inbound"), v.literal("outbound")),
    machineId: v.string(),
    sequence: v.number(),
    updatedAt: v.number(),
  }).index("by_machine_direction", ["machineId", "direction"]),

  // --- Extensibility tables (widen-only) ---

  slashCommands: defineTable({
    argumentHint: v.optional(v.string()),
    description: v.string(),
    machineId: v.id("machines"),
    name: v.string(),
    projectId: v.optional(v.id("projects")),
    scope: v.union(v.literal("builtin"), v.literal("project"), v.literal("user"), v.literal("skill")),
  }).index("by_project", ["projectId"]).index("by_machine", ["machineId"]),

  todos: defineTable({
    items: v.array(v.object({ content: v.string(), status: v.union(v.literal("pending"), v.literal("in_progress"), v.literal("completed")) })),
    threadId: v.id("threads"),
    updatedAt: v.number(),
  }).index("by_thread", ["threadId"]),

  operatorRoles: defineTable({
    grantedAt: v.number(),
    grantedBy: v.id("users"),
    userId: v.id("users"),
  }).index("by_user", ["userId"]),
});
