import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  machines: defineTable({
    capabilityCeiling: v.optional(v.array(v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task")))),
    deviceToken: v.string(),
    name: v.string(),
    platform: v.union(v.literal("darwin"), v.literal("linux"), v.literal("win32")),
    daemonVersion: v.string(),
    lastHeartbeatAt: v.number(),
  }).index("by_device_token", ["deviceToken"]),
  projects: defineTable({
    machineId: v.id("machines"),
    name: v.string(),
    path: v.string(),
  }).index("by_machine", ["machineId"]).index("by_machine_path", ["machineId", "path"]),
  threads: defineTable({
    activeAssistantMessageId: v.optional(v.id("messages")),
    budgetUsd: v.optional(v.number()),
    modelId: v.optional(v.string()),
    mode: v.optional(v.union(v.literal("chat"), v.literal("plan"))),
    planModelId: v.optional(v.string()),
    buildModelId: v.optional(v.string()),
    planPhase: v.optional(v.union(v.literal("planning"), v.literal("review"), v.literal("building"), v.literal("complete"))),
    projectId: v.id("projects"),
    status: v.union(v.literal("idle"), v.literal("queued"), v.literal("running"), v.literal("awaiting-approval"), v.literal("restoring"), v.literal("stopped"), v.literal("done"), v.literal("failed")),
    stopRequested: v.optional(v.boolean()),
    title: v.string(),
    thinkingLevel: v.optional(v.union(v.literal("none"), v.literal("low"), v.literal("medium"), v.literal("high"))),
    usageTotals: v.optional(v.object({
      cacheReadTokens: v.number(),
      cacheWriteTokens: v.number(),
      costUsd: v.number(),
      inputTokens: v.number(),
      outputTokens: v.number(),
      thinkingTokens: v.number(),
      thinkingTokensUnavailableCalls: v.number(),
    })),
  }).index("by_project", ["projectId"]),
  plans: defineTable({
    content: v.string(),
    revision: v.number(),
    status: v.union(v.literal("draft"), v.literal("approved")),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]),
  messages: defineTable({
    content: v.string(),
    queuedThreadId: v.optional(v.id("threads")),
    role: v.union(v.literal("assistant"), v.literal("user")),
    status: v.union(v.literal("complete"), v.literal("queued"), v.literal("streaming")),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]).index("by_status", ["status"]).index("by_queued_thread", ["queuedThreadId"]),
  events: defineTable({
    checkpointId: v.optional(v.id("checkpoints")),
    kind: v.union(v.literal("checkpoint.reverted"), v.literal("command.output"), v.literal("tool.completed")),
    output: v.optional(v.string()),
    summary: v.optional(v.string()),
    threadId: v.id("threads"),
    tool: v.optional(v.union(v.literal("bash"), v.literal("edit"), v.literal("read"), v.literal("task"))),
  }).index("by_thread", ["threadId"]),
  commands: defineTable({
    command: v.string(),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    threadId: v.id("threads"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]),
  diffs: defineTable({
    content: v.string(),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]),
  diffComments: defineTable({
    content: v.string(),
    endLine: v.number(),
    filePath: v.string(),
    resolved: v.boolean(),
    startLine: v.number(),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]),
  approvals: defineTable({
    capability: v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task")),
    decision: v.union(v.literal("pending"), v.literal("allow"), v.literal("deny")),
    risk: v.union(v.literal("low"), v.literal("high"), v.literal("critical")),
    resumeStatus: v.optional(v.union(v.literal("idle"), v.literal("queued"), v.literal("running"), v.literal("stopped"), v.literal("done"), v.literal("failed"))),
    summary: v.string(),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]),
  auditLog: defineTable({
    capability: v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task")),
    decision: v.union(v.literal("allow"), v.literal("deny"), v.literal("ask")),
    risk: v.union(v.literal("low"), v.literal("high"), v.literal("critical")),
    summary: v.string(),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]),
  gitActions: defineTable({
    action: v.union(v.literal("stage"), v.literal("commit"), v.literal("push")),
    message: v.optional(v.string()),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    threadId: v.id("threads"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]),
  checkpoints: defineTable({
    commit: v.string(),
    messageId: v.id("messages"),
    ref: v.string(),
    threadId: v.id("threads"),
  }).index("by_thread", ["threadId"]).index("by_message_id", ["messageId"]),
  checkpointActions: defineTable({
    checkpointId: v.id("checkpoints"),
    claimToken: v.optional(v.string()),
    leaseExpiresAt: v.optional(v.number()),
    resumeStatus: v.union(v.literal("idle"), v.literal("queued"), v.literal("stopped"), v.literal("done"), v.literal("failed")),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    threadId: v.id("threads"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]),
  checkpointComparisons: defineTable({
    claimToken: v.optional(v.string()),
    content: v.optional(v.string()),
    fromCheckpointId: v.id("checkpoints"),
    leaseExpiresAt: v.optional(v.number()),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    threadId: v.id("threads"),
    toCheckpointId: v.id("checkpoints"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]),
  usage: defineTable({
    cacheReadTokens: v.number(),
    cacheWriteTokens: v.number(),
    callId: v.string(),
    costUsd: v.number(),
    inputTokens: v.number(),
    messageId: v.id("messages"),
    modelId: v.string(),
    outputTokens: v.number(),
    role: v.string(),
    thinkingTokens: v.union(v.number(), v.null()),
    threadId: v.id("threads"),
  }).index("by_call_id", ["callId"]).index("by_thread", ["threadId"]),
  roles: defineTable({
    capabilities: v.array(v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task"))),
    contextMode: v.union(v.literal("fresh"), v.literal("forked")),
    description: v.string(),
    maxTurns: v.number(),
    modelId: v.string(),
    name: v.string(),
    prompt: v.string(),
    thinkingLevel: v.union(v.literal("none"), v.literal("low"), v.literal("medium"), v.literal("high")),
    writer: v.boolean(),
  }).index("by_name", ["name"]),
  subagentRuns: defineTable({
    capabilities: v.array(v.union(v.literal("read"), v.literal("edit"), v.literal("exec"), v.literal("task"))),
    claimToken: v.optional(v.string()),
    depth: v.number(),
    leaseExpiresAt: v.optional(v.number()),
    parentRunId: v.optional(v.id("subagentRuns")),
    result: v.optional(v.object({
      artifacts: v.array(v.string()),
      findings: v.array(v.string()),
      status: v.union(v.literal("success"), v.literal("failed")),
      summary: v.string(),
    })),
    roleId: v.id("roles"),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    task: v.string(),
    threadId: v.id("threads"),
  }).index("by_status", ["status"]).index("by_thread", ["threadId"]).index("by_parent_run_id", ["parentRunId"]),
});
