import { expect, test } from "bun:test";
import { DurableTaskStore, openMemoryStore } from "./index";
const task = { taskId: "task-1" as never, runId: "run-1" as never, role: "builder" as const, objective: "build", dependencies: [], capabilityCeiling: "workspace-write", contextBudget: 1000, workspaceMode: "isolated-worktree" as const, state: "ready" as const, attempt: 0, maxAttempts: 3 };
test("durable tasks survive reads and do not overwrite an active lease on retry", () => { const db = openMemoryStore(); const store = new DurableTaskStore(db); store.put(task, 1); store.put(task, 2); expect(store.get(task.taskId)?.objective).toBe("build"); expect(store.claim(task.taskId, "owner", 1000, 10)).toBe(1); expect(() => store.put({ ...task, state: "ready", objective: "different" }, 11)).toThrow("different immutable fields"); db.close(); });

test("expired claims are reclaimable and stale completions are fenced", () => { const db = openMemoryStore(); const store = new DurableTaskStore(db); store.put(task, 1); expect(store.claim(task.taskId, "owner-a", 10, 10)).toBe(1); expect(() => store.claim(task.taskId, "owner-b", 10, 19)).toThrow("not claimable"); expect(store.claim(task.taskId, "owner-b", 10, 20)).toBe(2); expect(store.complete(task.taskId, "owner-a", 1, { stale: true }, 21)).toBe(false); expect(store.complete(task.taskId, "owner-b", 2, { ok: true }, 22)).toBe(true); expect(store.get(task.taskId)?.state).toBe("completed"); expect(store.get(task.taskId)?.result).toEqual({ ok: true }); db.close(); });

test("expired running tasks return to the ready frontier", () => { const db = openMemoryStore(); const store = new DurableTaskStore(db); store.put(task, 1); store.claim(task.taskId, "owner", 10, 10); expect(store.reclaimExpired(19)).toBe(0); expect(store.reclaimExpired(20)).toBe(1); expect(store.get(task.taskId)?.state).toBe("ready"); db.close(); });

test("frontier only exposes tasks whose dependencies are complete", () => { const db = openMemoryStore(); const store = new DurableTaskStore(db); store.put({ ...task, taskId: "dependency" as never, state: "completed" }, 1); store.put({ ...task, taskId: "child" as never, dependencies: ["dependency" as never], state: "ready" }, 2); expect(store.frontier("run-1").map((item) => String(item.taskId))).toEqual(["child"]); db.close(); });
